{ pkgs, ... }: {
  environment.systemPackages = with pkgs; [
    vim
    neovim
    git
    foot
    #kitty
    alacritty
    #fish
    wget
    unzip
    firefox
    rofi-wayland
    wofi                                                                                                                                                    
    ags                                                                                                                                                                               
    openssh
    hugo                                                                                                                                                                              
    neofetch                                                                                                                                                                          
    btop 
    font-awesome  
    xfce.xfconf                                                                                                                                                                          
    xfce.thunar                                                                                                                                                                       
    xfce.thunar-volman 
    wl-clipboard 
    grim
    slurp
    swappy                                                                                                                                                    
    ags                                                                                                                                                                               
    networkmanager-openvpn
    openvpn 
    pulseaudio
    pavucontrol                                                                                                                                                                             
    powertop 
    udiskie
    gvfs 
  ];                            
}